card_create:
    path:     /{id}/create
    defaults: { _controller: "TrelloAppBundle:Card:create" }
    methods:  POST

card_update:
    path:     /{id}/update
    defaults: { _controller: "TrelloAppBundle:Card:update" }
    methods:  [POST, PUT]

card_archived:
    path:     /{id}/archived
    defaults: { _controller: "TrelloAppBundle:Card:archived" }
    methods:  [POST, PUT]

card_delete:
    path:     /{id}/delete
    defaults: { _controller: "TrelloAppBundle:Card:delete" }
    methods:  [POST, DELETE]
