liste_create:
    path:     /{id}/create
    defaults: { _controller: "TrelloAppBundle:Liste:create" }
    methods:  POST


liste_delete:
    path:     /{id}/delete
    defaults: { _controller: "TrelloAppBundle:Liste:delete" }
    methods:  [POST, DELETE]
